# -*- coding: utf-8 -*-
"""vae_anomaly_detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPA35dOQyOH7bFNRDLGpuWiNYXqGnuvK
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc
from sklearn.preprocessing import StandardScaler

# 1. DATA GENERATION
def generate_data(n_samples=10000, n_features=100, anomaly_fraction=0.05):
    np.random.seed(42)
    # Normal data: Mean 0, Std 1
    X = np.random.randn(n_samples, n_features)
    y = np.zeros(n_samples)

    # Adding Anomalies (Extreme Outliers)
    n_anomalies = int(n_samples * anomaly_fraction)
    indices = np.random.choice(n_samples, n_anomalies, replace=False)
    X[indices] += np.random.uniform(5, 10, size=(n_anomalies, n_features))
    y[indices] = 1

    return X.astype(np.float32), y

# 2. VAE ARCHITECTURE
class VAE(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, latent_dim=10):
        super(VAE, self).__init__()
        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU()
        )
        self.fc_mu = nn.Linear(hidden_dim // 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim // 2, latent_dim)

        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, input_dim)
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        h = self.encoder(x)
        mu, logvar = self.fc_mu(h), self.fc_logvar(h)
        z = self.reparameterize(mu, logvar)
        return self.decoder(z), mu, logvar

# 3. LOSS FUNCTION (with Beta-VAE support)
def loss_function(recon_x, x, mu, logvar, beta=1.0):
    recon_loss = nn.MSELoss(reduction='sum')(recon_x, x)
    # KL Divergence
    kld_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + (beta * kld_loss)

# 4. TRAINING & EVALUATION
def train_and_evaluate():
    # Setup
    X, y = generate_data()
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X[y == 0]) # Train only on normal data
    X_test = scaler.transform(X)

    train_loader = DataLoader(TensorDataset(torch.from_numpy(X_train)), batch_size=64, shuffle=True)
    test_tensor = torch.from_numpy(X_test)

    model = VAE(input_dim=100)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    # Training Loop
    model.train()
    for epoch in range(20):
        total_loss = 0
        for batch in train_loader:
            optimizer.zero_grad()
            recon, mu, logvar = model(batch[0])
            loss = loss_function(recon, batch[0], mu, logvar, beta=1.5)
            loss.backward()
            total_loss += loss.item()
            optimizer.step()

    # Anomaly Scoring
    model.eval()
    with torch.no_grad():
        recon_test, mu_test, logvar_test = model(test_tensor)

        # Scoring: Reconstruction Error + Latent Distance (Mahalanobis-style)
        recon_errors = torch.mean((recon_test - test_tensor)**2, dim=1)
        latent_dist = torch.sum(mu_test**2, dim=1) # Distance from center of N(0,1)
        scores = (recon_errors + 0.1 * latent_dist).numpy()

    # Metrics
    auc_roc = roc_auc_score(y, scores)
    precision, recall, _ = precision_recall_curve(y, scores)
    pr_auc = auc(recall, precision)

    print(f"AUC-ROC Score: {auc_roc:.4f}")
    print(f"PR-AUC Score: {pr_auc:.4f}")

if __name__ == "__main__":
    train_and_evaluate()